# Generated by Django 3.1.5 on 2021-02-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
